/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.Address;
import Controller.CNPJNotValidException;
import Controller.CharacterLimitException;
import Controller.ComboMultiData;
import Controller.Hotel;
import Controller.User;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;


/**
 *
 * @author Marcos
 */
public class JFAddHotel extends javax.swing.JFrame {

    /**
     * Creates new form JFAddHotel
     */
    private User user = null;
    private Set<File> photos = new HashSet();
    
    public void load_user(User user)
    {
        this.user = user;
    }
    
    public void fulfillComponents(String type) throws SQLException
    {
        Vector <ComboMultiData> v = new Vector();
        Address a = new Address();
        v = a.list(type);
        DefaultComboBoxModel model = new DefaultComboBoxModel(v);
        switch(type)
        {
            case "countries" :
                jComboCountries.setModel(model);
                break;
            case "states" :
                jComboStates.setModel(model);
                break;
            case "cities" :
                jComboCities.setModel(model);
                break;
        }
    }
    
    public void fulfillComponents(String type, int index) throws SQLException
    {
        Vector <ComboMultiData> v = new Vector();
        Address address = new Address();
        v = address.list(type, index);
        DefaultComboBoxModel model = new DefaultComboBoxModel(v);
        switch(type)
        {
            case "countries" :
                jComboCountries.setModel(model);
                break;
            case "states" :
                jComboStates.setModel(model);
                break;
            case "cities" :
                jComboCities.setModel(model);
                break;
        }
    }
    
    public void cleanComponents()
    {
        jTxtCNPJ.setText("");
        jTxtAreaDrescription.selectAll();
        jTxtAreaDrescription.setText("");
        jTxtBedroomsNumber.setText("");
        jTxtHotelDailyRate.setText("");
        jTxtHotelName.setText("");
        jTxtAddress.setText("");
        jComboCountries.setSelectedIndex(0);
        jComboStates.setSelectedIndex(0);
        jComboCities.setSelectedIndex(0);
    }
    
    public JFAddHotel() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        jComboCountries.removeAllItems();
        jComboStates.removeAllItems();
        jComboCities.removeAllItems();
        jComboCountries.addItem("- Selecione um país -");
        fulfillComponents("countries");
        jTxtAreaDrescription.setColumns(300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtHotelName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtAreaDrescription = new java.awt.TextArea();
        jTxtBedroomsNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtHotelDailyRate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBtnAddImages = new javax.swing.JButton();
        jLblPhotoQuantity = new javax.swing.JLabel();
        jBtnSave = new javax.swing.JButton();
        jBtnClean = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTxtCNPJ = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboCountries = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboStates = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboCities = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guia Hoteleiro - Cadastro de Hotel");
        setResizable(false);

        jLabel1.setText("Nome do Hotel");

        jLabel2.setText("Descrição");

        jTxtAreaDrescription.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setText("Num. Quartos");

        jLabel4.setText("Diária - R$");

        jBtnAddImages.setText("Adicionar imagens");
        jBtnAddImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddImagesActionPerformed(evt);
            }
        });

        jLblPhotoQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblPhotoQuantity.setText("Nenhuma foto selecionada");

        jBtnSave.setText("Salvar");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jBtnClean.setText("Limpar");
        jBtnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCleanActionPerformed(evt);
            }
        });

        jBtnExit.setText("Sair");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        jLabel9.setText("CNPJ");

        jLabel10.setText("Endereço");

        jLabel5.setText("País");

        jComboCountries.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboCountries.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboCountriesItemStateChanged(evt);
            }
        });

        jLabel6.setText("Estado");

        jComboStates.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboStates.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboStatesItemStateChanged(evt);
            }
        });

        jLabel7.setText("Cidade");

        jComboCities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Máximo de 1000 caracteres");
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnClean, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblPhotoQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnAddImages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboCities, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboStates, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboCountries, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtHotelDailyRate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtBedroomsNumber)
                            .addComponent(jBtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtHotelName)
                            .addComponent(jTxtAreaDrescription, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtCNPJ, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTxtAreaDrescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtBedroomsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtHotelDailyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboCountries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboStates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAddImages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblPhotoQuantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnClean)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddImagesActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setMultiSelectionEnabled(true);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");
        jfc.setFileFilter(filter);
        
        int returnValue = jfc.showOpenDialog(null);
        
        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
            File[] files = jfc.getSelectedFiles();
            for(int i = 0; i < files.length; i++)
            {
                photos.add(files[i]);
            }
            
            if(files.length == 1)
                jLblPhotoQuantity.setText(String.valueOf(files.length) + " Foto Selecionada");
            else if(files.length > 1)
                jLblPhotoQuantity.setText(String.valueOf(files.length) + " Fotos Selecionadas");
        }
    }//GEN-LAST:event_jBtnAddImagesActionPerformed

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        Hotel h = new Hotel();
        h.setCnpj(jTxtCNPJ.getText());
        h.setHotel_name(jTxtHotelName.getText());
        h.setHotel_description(jTxtAreaDrescription.getText());
        if(jTxtBedroomsNumber.getText().isEmpty())
            h.setBedrooms_number(0);
        else
            h.setBedrooms_number(Integer.parseInt(jTxtBedroomsNumber.getText()));
        if(jTxtHotelDailyRate.getText().isEmpty())
            h.setHotel_daily_rate(0.00);
        else
            h.setHotel_daily_rate(Double.parseDouble(jTxtHotelDailyRate.getText().replace(",", ".")));
        h.setHotel_photos(photos);
        
        try
        {
            if(h.addHotel(h, user.getUser_id()))
            {
                Address a = new Address();
                a.setAddress(jTxtAddress.getText());
                a.setCity(((ComboMultiData)jComboCities.getSelectedItem()).getValue());
                a.setAddress_type("H");

                if(a.addAddress(a, h.getCnpj()))
                {
                    JOptionPane.showMessageDialog(null, "Registro realizado com sucesso!");
                    this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(null, "Registro falhou!");
            }
        }
        catch (CNPJNotValidException | CharacterLimitException |SQLException | IOException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jComboStatesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboStatesItemStateChanged
        int index = jComboStates.getSelectedIndex() + 1;
        try
        {
            fulfillComponents("cities", index);
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jComboStatesItemStateChanged

    private void jComboCountriesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboCountriesItemStateChanged
        int index = jComboCountries.getSelectedIndex() + 1;
        try
        {
            fulfillComponents("states", index);
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jComboCountriesItemStateChanged

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jBtnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCleanActionPerformed
        cleanComponents();
    }//GEN-LAST:event_jBtnCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    new JFAddHotel().setVisible(true);
                }
                catch (SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddImages;
    private javax.swing.JButton jBtnClean;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JComboBox<String> jComboCities;
    private javax.swing.JComboBox<String> jComboCountries;
    private javax.swing.JComboBox<String> jComboStates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblPhotoQuantity;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jTxtAddress;
    private java.awt.TextArea jTxtAreaDrescription;
    private javax.swing.JTextField jTxtBedroomsNumber;
    private javax.swing.JTextField jTxtCNPJ;
    private javax.swing.JTextField jTxtHotelDailyRate;
    private javax.swing.JTextField jTxtHotelName;
    // End of variables declaration//GEN-END:variables
}
