/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.Address;
import Controller.CPFNotValidException;
import Controller.ComboMultiData;
import Controller.User;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */

public class JFRegister extends javax.swing.JFrame
{

    /**
     * Creates new form JFRegister
     */
    
    public void fulfillComponents(String type) throws SQLException
    {
        Vector <ComboMultiData> v = new Vector();
        Address a = new Address();
        v = a.list(type);
        DefaultComboBoxModel model = new DefaultComboBoxModel(v);
        switch(type)
        {
            case "countries" :
                jComboCountries.setModel(model);
                break;
            case "states" :
                jComboStates.setModel(model);
                break;
            case "cities" :
                jComboCities.setModel(model);
                break;
        }
    }
    
    public void fulfillComponents(String type, int index) throws SQLException
    {
        Vector <ComboMultiData> v = new Vector();
        Address address = new Address();
        v = address.list(type, index);
        DefaultComboBoxModel model = new DefaultComboBoxModel(v);
        switch(type)
        {
            case "countries" :
                jComboCountries.setModel(model);
                break;
            case "states" :
                jComboStates.setModel(model);
                break;
            case "cities" :
                jComboCities.setModel(model);
                break;
        }
    }
    
    public void cleanComponents()
    {
        jTxtCPF.setText("");
        jTxtPassword.setText("");
        jTxtName.setText("");
        jTxtAge.setText("");
        jTxtAddress.setText("");
        jComboCountries.setSelectedIndex(0);
        jComboStates.setSelectedIndex(0);
        jComboCities.setSelectedIndex(0);
    }
    
    public void register() throws CPFNotValidException, SQLException
    {
        User user = new User();
        user.setCpf(jTxtCPF.getText());
        user.setPassword(String.valueOf(jTxtPassword.getPassword()));
        user.setUser_name(jTxtName.getText());
        if(!jTxtAge.getText().isEmpty())
            user.setAge(Integer.parseInt(jTxtAge.getText()));
        if(jChkOwner.getState())
            user.setProfile("O");
        else
            user.setProfile("U");
        
        if(user.register(user))
        {
            Address a = new Address();
            a.setAddress(jTxtAddress.getText());
            a.setCity(((ComboMultiData)jComboCities.getSelectedItem()).getValue());
            a.setAddress_type("U");
            
            if(a.addAddress(a, user.getCpf()))
            {
                JOptionPane.showMessageDialog(null, "Registro realizado com sucesso!");
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(null, "Registro falhou!");
        }
        else
            JOptionPane.showMessageDialog(null, "Registro falhou!");
        
    }
    
    public JFRegister() throws SQLException
    {
        initComponents();
        jComboCountries.removeAllItems();
        jComboStates.removeAllItems();
        jComboCities.removeAllItems();
        jComboCountries.addItem("- Selecione um país -");
        fulfillComponents("countries");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtCPF = new javax.swing.JTextField();
        jTxtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jTxtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboCountries = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboStates = new javax.swing.JComboBox<>();
        jComboCities = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBtnSave = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jBtnClean = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtAge = new javax.swing.JTextField();
        jChkOwner = new java.awt.Checkbox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guia Hoteleiro - Registro");
        setResizable(false);

        jLabel1.setText("CPF");

        jLabel2.setText("Password");

        jLabel3.setText("Endereço");

        jComboCountries.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboCountries.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboCountriesItemStateChanged(evt);
            }
        });

        jLabel4.setText("País");

        jComboStates.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboStates.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboStatesItemStateChanged(evt);
            }
        });

        jComboCities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Estado");

        jLabel6.setText("Cidade");

        jBtnSave.setText("Salvar");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jBtnExit.setText("Sair");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        jBtnClean.setText("Limpar");
        jBtnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCleanActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome");

        jLabel8.setText("Idade");

        jChkOwner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jChkOwner.setLabel("Seja um membro associado e gerencie seus hoteis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(jTxtCPF)
                            .addComponent(jTxtName)
                            .addComponent(jTxtAge)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jChkOwner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboCities, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboStates, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboCountries, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtAddress)
                            .addComponent(jBtnClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboCountries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboStates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jChkOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnClean)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jComboStatesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboStatesItemStateChanged
        int index = jComboStates.getSelectedIndex() + 1;
        try
        {
            fulfillComponents("cities", index);
        }
        catch (SQLException ex)
        {
            Logger.getLogger(JFRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboStatesItemStateChanged

    private void jComboCountriesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboCountriesItemStateChanged
        int index = jComboCountries.getSelectedIndex() + 1;
        try
        {
            fulfillComponents("states", index);
        }
        catch (SQLException ex)
        {
            Logger.getLogger(JFRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboCountriesItemStateChanged

    private void jBtnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCleanActionPerformed
        cleanComponents();
    }//GEN-LAST:event_jBtnCleanActionPerformed

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        try
        {
            register();
        }
        catch (CPFNotValidException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        catch (SQLException ex)
        {
            Logger.getLogger(JFRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFRegister().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFRegister.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClean;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnSave;
    private java.awt.Checkbox jChkOwner;
    private javax.swing.JComboBox<String> jComboCities;
    private javax.swing.JComboBox<String> jComboCountries;
    private javax.swing.JComboBox<String> jComboStates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtAge;
    private javax.swing.JTextField jTxtCPF;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JPasswordField jTxtPassword;
    // End of variables declaration//GEN-END:variables

}
